### PR TITLE
Adding support for maps to encode() and fixing README

### PR DESCRIPTION
**Pull request by akovari**
This can be useful especially with nested maps inside maps.

### CODE REVIEW

**Comment by rvirding** [comment]
I will merge this during the weekend. Unfortunately we can't use maps internally to store Lua tables as the maps interface is lacking some crucial functions. We would need first/next functions to allow us to step through a map in the Lua way. I can fake it but it would be inefficient.

**Comment by rvirding** [comment]
There is one problem with adding maps in that way to luerl, it will no longer compile on Erlang versions older than 17 as they don't have maps. This can be fixed by basically taking the same fix as I do in lfe but it is a little more work.

**Comment by rvirding** [comment]
Finally getting around to this. There is one small error in the README fix, in the call to `luerl:do` the argument should be a binary:

    luerl:do(<<"print(inc(4))">>, State1)

**Comment by rvirding** [comment]
Could you now do one more thing and I will pull it? That is to rebase on the current develop branch. That will keep the network cleaner which I like. Thanks.

**Comment by akovari** [comment]
I've rebased the branch. To be honest, I don't know Lua that well so I can't tell easily what else is missing in proper support for erlang maps. I could probably do a bit more work on this but I'd need some pointers / instructions.  Anyway, thanks for your help and time.

**Comment by rvirding** [comment]
Supporting maps on the erlang side is not difficult, your encode did half the work. What is left there is decode and the issue with that is how to handle converting lua tables. Should they go to a map or remain a property list as they are now?

Using maps internally is a bit more tricky. Maps would work well for lua tables except that the existing map interface in erlang[*] is missing a few functions. There is no direct support for implementing the lua `next` function, nothing that gives you the "first" key/value element and one that gives you the "next" key/value element after a specific key. Without these two functions doing lua `next` becomes very inefficient. I tried to get them to add first/next functions to maps but they weren't interested. Unfortunately there are no extra NIF functions that re helpful

So for the time being we will keep the existing implementation which uses arrays for the array part of a table and special dictionary module for the rest.

[*] Same for both elixir and LFE which of course use the same interface.

**Pull request merged**
