### PR TITLE
Changes for hex.pm package

### LINKED ISSUE #72: hex package
It would be really nice to have a hex package for luerl!

I think it's pretty much only needed to run `rebar3 hex publish` if not I'm happy to publish it, work out all the kinks, prepare a PR and then hand the package over.

### PR DESCRIPTION
**Pull request by Licenser**
Changes for the hex package (really not manny). I've published this as a test and gladly hand over the ownership just need the e-mail you used to for hex.pm :)

Resolves #72

### CODE REVIEW

**Comment by Licenser** [comment]
https://hex.pm/packages/luerl

**Comment by rvirding** [comment]
I have fallen a bit behind. Could you please just rebase this and I will pull it.

**Comment by Licenser** [comment]
aye, done and published new changes as 0.3.1 :)

**Comment by jchassoul** [comment]
awesome! this needs to be included in the docs! (= I don't know hex currently I have been around erlang.mk let's do both!

**Comment by Licenser** [comment]
based on their docs erlang.mk can use hex packages: https://erlang.mk/guide/plugins_list.html no need to doublicate work for library maintainers

**Comment by jchassoul** [comment]
erlang.mk is no package manager is more a simple build tool for good old unix makefiles there is no double work for library maintainers it currently builds directly from this git repo.

It's awesome to have luerl available on hex given the great use that the hex package manager brings to the erlang ecosystem and it's great to have also simple tools like erlang.mk it's all good to have options.

**Comment by Licenser** [comment]
If this repo works out of the box and there is nothing extra to do then I'm not sure what you mean with "do both"?

**Comment by jchassoul** [comment]
I'm sorry I was talking about the docs, how to get luerl from both hex and erlang.mk which is great to have the options.

**Comment by jchassoul** [comment]
Hmmm, after some testing the installation of luerl from erlang.mk is broken I have tested directly as it currently is in the get started page and also with dep_luerl = hex 0.3.1 as I read hex.pm recommends.

This relates with #88 I'm going to continue looking for the cause (= I tested using my fork of luerl pre this merge on deps and it builds, that ping-pong got me here, it does not work after the hex.pm changes.

**Pull request merged**
