### PR TITLE
Implements most of the os.date() function.

### PR DESCRIPTION
**Pull request by markmeeus**
I added most of the `os.date` formatting in this PR.
All the formatting is in a separate luerl_date_support module.

### CODE REVIEW

**Comment by rvirding** [comment]
I would like to pull this but would like to change the name of the file to `luerl_lib_os_date.erl` to make it conform to the naming convention that I have used. Could you do that for me. There are conflicts whch need fixing but it is easier if I do those.

**Comment by markmeeus** [comment]
Sure, I'll do that one of these days.

**Comment by rvirding** [comment]
@markmeeus I made mistake when I updated it and needed to pull it down to me to fix it. I then forced a push over the generated one but now everything is good.

**Comment by markmeeus** [comment]
Thanks @rvirding !

**Pull request merged**
